name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli

    - name: Build project
      run: npm run build

    - name: Start server and run Lighthouse CI
      run: |
        npx serve@latest out &
        lhci autorun